[package]
name = "rustaxa-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
ethereum-types = { version = "0.16.0", features = ["rlp"] }
k256 = { version = "0.13", features = ["ecdsa"] }
rlp = "0.6"
rustaxa-types = { path = "../rustaxa-types" }
thiserror = "2.0.17"
tiny-keccak = { version = "2.0", features = ["keccak"] }

[dependencies.rocksdb]
version = "0.24.0"
default-features = false
features = ["lz4"]
