[package]
name = "rustaxa-evm"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.100"
rustaxa-types = { path = "../rustaxa-types" }
num-bigint = "0.4.6"
revm = { git = "https://github.com/bluealloy/revm.git", rev = "6014612c86f3690e4e9173a8c4deade396af398d", default-features = false, features = ["std"] }

[dev-dependencies]
hex = "0.4"
ethereum-types = { version = "0.16.0", features = ["rlp"] }
k256 = { version = "0.13", features = ["ecdsa"] }
rlp = "0.6"
rustaxa-consensus = { path = "../rustaxa-consensus" }
rustaxa-storage = { path = "../rustaxa-storage" }
serde_json = "1.0.145"
