#!/usr/bin/env bash

set -euo pipefail

# The arguments to this script will be passed directly to `pytest`. Run this script with `--setup-only` to only
# set up the environment without running tests. For interactive development, google how to activate/use virtual env,
# which will be generated by this script in `./venv`.
# Run this script with `--help` to see the command line reference for the testing project itself.

cd "$(dirname "$0")"

if [[ $(uname -m) == "aarch64" ]]; then
  echo "pytests currently are not supported on arm because the pinned solc package is unavailable"
  exit 0
fi

python_bin=${PYTHON_BIN:-python3.11}
if ! command -v "$python_bin" >/dev/null 2>&1; then
  echo "Error: Python 3.11 is required (set PYTHON_BIN to an explicit Python 3.11 executable)." >&2
  exit 1
fi
if ! "$python_bin" -c 'import sys; raise SystemExit(sys.version_info[:2] != (3, 11))'; then
  echo "Error: $python_bin is not Python 3.11." >&2
  exit 1
fi

"$python_bin" -m venv --clear venv
venv/bin/python -m pip install --disable-pip-version-check --requirement requirements.txt

# Keep the legacy Solidity-backed RPC fixture reproducible without relying on
# an image-specific compiler installation. py-solc-x discovers versioned
# executables from SOLCX_BINARY_PATH; the release asset is pinned by digest.
solc_version=0.6.12
solc_sha256=f6cb519b01dabc61cab4c184a3db11aa591d18151e362fcae850e42cffdfb09a
solcx_binary_path=${SOLCX_BINARY_PATH:-/tmp/rustaxa-solcx}
solc_binary="$solcx_binary_path/solc-v$solc_version"
mkdir -p "$solcx_binary_path"
if [[ ! -x "$solc_binary" ]] || ! echo "$solc_sha256  $solc_binary" | sha256sum --check --status; then
  curl --location --fail --retry 3 \
    --output "$solc_binary" \
    "https://github.com/ethereum/solidity/releases/download/v$solc_version/solc-static-linux"
  echo "$solc_sha256  $solc_binary" | sha256sum --check
  chmod +x "$solc_binary"
fi
export SOLCX_BINARY_PATH="$solcx_binary_path"

if [[ ${1:-} == "--setup-only" ]]; then
  exit 0
fi
exec venv/bin/python -m pytest "$@"
