//! CXX bridge wrappers for Rust PBFT vote generation.
//!
//! The bridge exposes a byte-oriented generation contract to the C++
//! `VoteManager` shim. Rust composes weighted generation with borrowed
//! FinalChain state; C++ retains wallet selection and temporary live `PbftVote`
//! materialization from canonical Rust-generated bytes.

use crate::ffi::rustaxa_ffi::{
    PbftFinalChainDposAddressVoteFact as FfiPbftFinalChainDposAddressVoteFact,
    PbftFinalChainDposTotalVoteCountFacts as FfiPbftFinalChainDposTotalVoteCountFacts,
    PbftFinalChainDposTotalVoteCountRequest as FfiPbftFinalChainDposTotalVoteCountRequest,
    PbftFinalChainDposWalletAggregateVoteCountFacts as FfiPbftFinalChainDposWalletAggregateVoteCountFacts,
    PbftFinalChainDposWalletAggregateVoteCountRequest as FfiPbftFinalChainDposWalletAggregateVoteCountRequest,
    PbftFinalChainDposWalletEligibilityBatchFacts as FfiPbftFinalChainDposWalletEligibilityBatchFacts,
    PbftFinalChainDposWalletEligibilityBatchRequest as FfiPbftFinalChainDposWalletEligibilityBatchRequest,
    PbftFinalChainDposWalletEligibilityFacts as FfiPbftFinalChainDposWalletEligibilityFacts,
    PbftFinalChainDposWalletEligibilityRequest as FfiPbftFinalChainDposWalletEligibilityRequest,
    PbftGeneratedVote as FfiPbftGeneratedVote,
    PbftProposerSortitionRequest as FfiPbftProposerSortitionRequest,
    PbftProposerSortitionResult as FfiPbftProposerSortitionResult,
    PbftVoteGenerationInput as FfiPbftVoteGenerationInput,
};
use crate::ffi::{BridgeFinalChain, BridgePbftService};
use anyhow::{anyhow, Result};
use ethereum_types::{H160, H256};
use rustaxa_consensus::pbft_vote_generation::{
    generate_pbft_vote, generate_pbft_vote_with_weight, PbftGeneratedVote, PbftVoteGenerationInput,
    PbftVoteWeightFacts,
};
use rustaxa_consensus::pbft_vote_validation::{
    generate_and_validate_proposer_sortition_with_prepared_request,
    prepare_and_validate_pbft_proposer_sortition_request, PbftProposerSortitionRequest,
    PbftProposerSortitionResult,
};
use rustaxa_consensus::verified_votes::PbftVoteType;

const PBFT_FINAL_CHAIN_FACT_STATUS_READY: u8 = 0;
const PBFT_FINAL_CHAIN_FACT_STATUS_UNAVAILABLE: u8 = 1;

/// Generates one signed PBFT vote payload in Rust.
pub fn pbft_generate_signed_vote(
    input: FfiPbftVoteGenerationInput,
) -> Result<FfiPbftGeneratedVote> {
    Ok(generate_pbft_vote(input.try_into()?)?.into())
}

impl BridgePbftService {
    /// Generates one canonical signed and weighted PBFT vote from live Rust FinalChain state.
    ///
    /// The caller supplies wallet/signing input and immutable committee configuration. The
    /// operation converts the PBFT period to its DPoS period, reads voter stake before total
    /// stake, and delegates deterministic signing and weighting to `rustaxa-consensus`. Zero
    /// stake, zero total stake, and zero weight remain typed generation outcomes. Period
    /// underflow, future state, and unavailable/corrupt snapshots are boundary errors. No PBFT
    /// service lock or FinalChain handle is retained after the synchronous call.
    pub fn pbft_service_generate_signed_vote_with_weight(
        &self,
        final_chain: &BridgeFinalChain,
        input: FfiPbftVoteGenerationInput,
        committee_size: u64,
        number_of_proposers: u64,
    ) -> Result<FfiPbftGeneratedVote> {
        let input: PbftVoteGenerationInput = input.try_into()?;
        let dpos_period = input
            .period
            .checked_sub(1)
            .ok_or_else(|| anyhow!("PBFT_VOTE_GENERATION_PERIOD_UNDERFLOW"))?;
        let voter = input.expected_voter;

        let voter_dpos_vote_count = match final_chain
            .0
            .pbft_dpos_eligible_vote_count(dpos_period, voter.0)
        {
            Ok(Some(votes)) => votes,
            Ok(None) => anyhow::bail!("PBFT_FINAL_CHAIN_ADDRESS_FACT_FUTURE_PERIOD"),
            Err(err) => anyhow::bail!("PBFT_FINAL_CHAIN_ADDRESS_FACT_UNAVAILABLE: {err}"),
        };
        if voter_dpos_vote_count == 0 {
            return Ok(generate_pbft_vote_with_weight(
                input,
                PbftVoteWeightFacts {
                    voter_dpos_vote_count,
                    total_dpos_vote_count: 0,
                    committee_size,
                    number_of_proposers,
                },
            )?
            .into());
        }
        let total_dpos_vote_count = match final_chain
            .0
            .pbft_dpos_eligible_total_vote_count(dpos_period)
        {
            Ok(Some(total)) => total,
            Ok(None) => anyhow::bail!("PBFT_FINAL_CHAIN_TOTAL_VOTES_FACT_FUTURE_PERIOD"),
            Err(err) => anyhow::bail!("PBFT_FINAL_CHAIN_TOTAL_VOTES_FACT_UNAVAILABLE: {err}"),
        };
        let facts = PbftVoteWeightFacts {
            voter_dpos_vote_count,
            total_dpos_vote_count,
            committee_size,
            number_of_proposers,
        };
        Ok(generate_pbft_vote_with_weight(input, facts)?.into())
    }

    /// Generates proposer-sortition proof inputs and validates local proposer weight.
    ///
    /// The caller supplies raw FinalChain voter identity and DPoS facts are read
    /// from `final_chain` by PBFT period semantics (`dpos_period = pbft_period - 1`).
    /// Identity and proof validation errors are returned as boundary errors.
    pub fn pbft_service_generate_and_validate_proposer_sortition(
        &self,
        final_chain: &BridgeFinalChain,
        request: FfiPbftProposerSortitionRequest,
    ) -> Result<FfiPbftProposerSortitionResult> {
        let request = PbftProposerSortitionRequest::try_from(request)?;
        let request = prepare_and_validate_pbft_proposer_sortition_request(request)?;
        let dpos_period = request
            .request
            .pbft_period
            .checked_sub(1)
            .ok_or_else(|| anyhow!("PBFT_PROPOSER_SORTITION_PERIOD_UNDERFLOW"))?;

        let voter_dpos_vote_count = match final_chain
            .0
            .pbft_dpos_eligible_vote_count(dpos_period, request.request.expected_voter.0)
        {
            Ok(Some(votes)) => votes,
            Ok(None) => {
                return Ok(PbftProposerSortitionResult::rejected(
                    rustaxa_consensus::pbft_vote_validation::PbftProposerSortitionStatus::FutureDposState,
                )
                .into())
            }
            Err(err) => anyhow::bail!("PBFT_FINAL_CHAIN_ADDRESS_FACT_UNAVAILABLE: {err}"),
        };

        if voter_dpos_vote_count == 0 {
            return Ok(PbftProposerSortitionResult::rejected(
                rustaxa_consensus::pbft_vote_validation::PbftProposerSortitionStatus::ZeroStake,
            )
            .into());
        }

        let total_dpos_vote_count = match final_chain.0.pbft_dpos_eligible_total_vote_count(dpos_period)
        {
            Ok(Some(total)) => total,
            Ok(None) => {
                return Ok(PbftProposerSortitionResult::rejected(
                    rustaxa_consensus::pbft_vote_validation::PbftProposerSortitionStatus::FutureDposState,
                )
                .into())
            }
            Err(err) => anyhow::bail!("PBFT_FINAL_CHAIN_TOTAL_VOTES_FACT_UNAVAILABLE: {err}"),
        };

        Ok(
            generate_and_validate_proposer_sortition_with_prepared_request(
                request,
                voter_dpos_vote_count,
                total_dpos_vote_count,
            )?
            .into(),
        )
    }

    /// Queries PBFT-facing total DPoS-vote facts for an exact period.
    ///
    /// `Ok(None)` period availability is projected as
    /// `PBFT_FINAL_CHAIN_FACT_STATUS_UNAVAILABLE` with a dedicated error string.
    pub fn pbft_service_collect_dpos_total_vote_count(
        &self,
        final_chain: &BridgeFinalChain,
        request: FfiPbftFinalChainDposTotalVoteCountRequest,
    ) -> Result<FfiPbftFinalChainDposTotalVoteCountFacts> {
        let last_block_number = final_chain.0.last_block_number()?;
        let (status, has_total_vote_count, total_vote_count, error_code) = match final_chain
            .0
            .pbft_dpos_eligible_total_vote_count(request.period)
        {
            Ok(Some(total_vote_count)) => (
                PBFT_FINAL_CHAIN_FACT_STATUS_READY,
                true,
                total_vote_count,
                String::new(),
            ),
            Ok(None) => (
                PBFT_FINAL_CHAIN_FACT_STATUS_UNAVAILABLE,
                false,
                0,
                "PBFT_FINAL_CHAIN_TOTAL_VOTES_FUTURE_PERIOD".to_string(),
            ),
            Err(err) => (
                PBFT_FINAL_CHAIN_FACT_STATUS_UNAVAILABLE,
                false,
                0,
                format!("PBFT_FINAL_CHAIN_TOTAL_VOTES_UNAVAILABLE: {err}"),
            ),
        };

        Ok(FfiPbftFinalChainDposTotalVoteCountFacts {
            status,
            last_block_number,
            has_total_vote_count,
            total_vote_count,
            error_code,
        })
    }

    /// Queries PBFT-facing aggregate DPoS-vote facts for a supplied wallet subset.
    ///
    /// The aggregate is the simple sum of wallet eligible vote counts. Futures and
    /// storage corruption are returned as unavailable data using typed status/error
    /// codes instead of silently returning partial totals.
    pub fn pbft_service_collect_dpos_wallet_aggregate_vote_count(
        &self,
        final_chain: &BridgeFinalChain,
        request: FfiPbftFinalChainDposWalletAggregateVoteCountRequest,
    ) -> Result<FfiPbftFinalChainDposWalletAggregateVoteCountFacts> {
        let last_block_number = final_chain.0.last_block_number()?;
        let addresses = request
            .addresses
            .into_iter()
            .map(|entry| entry.address)
            .collect::<Vec<_>>();
        let (status, has_aggregate_vote_count, aggregate_vote_count, error_code) =
            if addresses.is_empty() {
                (PBFT_FINAL_CHAIN_FACT_STATUS_READY, true, 0, String::new())
            } else {
                match final_chain
                    .0
                    .pbft_dpos_eligible_wallet_vote_counts(request.period, &addresses[..])
                {
                    Ok(Some(votes)) => {
                        let aggregate_vote_count = votes
                            .iter()
                            .fold(0_u64, |total, vote| total.wrapping_add(vote.vote_count));
                        (
                            PBFT_FINAL_CHAIN_FACT_STATUS_READY,
                            true,
                            aggregate_vote_count,
                            String::new(),
                        )
                    }
                    Ok(None) => (
                        PBFT_FINAL_CHAIN_FACT_STATUS_UNAVAILABLE,
                        false,
                        0,
                        "PBFT_FINAL_CHAIN_WALLET_VOTES_FUTURE_PERIOD".to_string(),
                    ),
                    Err(err) => (
                        PBFT_FINAL_CHAIN_FACT_STATUS_UNAVAILABLE,
                        false,
                        0,
                        format!("PBFT_FINAL_CHAIN_WALLET_VOTES_UNAVAILABLE: {err}"),
                    ),
                }
            };

        Ok(FfiPbftFinalChainDposWalletAggregateVoteCountFacts {
            status,
            last_block_number,
            has_aggregate_vote_count,
            aggregate_vote_count,
            error_code,
        })
    }

    /// Queries PBFT-facing single-wallet DPoS vote facts for one address.
    pub fn pbft_service_collect_dpos_wallet_eligibility(
        &self,
        final_chain: &BridgeFinalChain,
        request: FfiPbftFinalChainDposWalletEligibilityRequest,
    ) -> Result<FfiPbftFinalChainDposWalletEligibilityFacts> {
        let last_block_number = final_chain.0.last_block_number()?;
        let (status, vote_count, error_code) = match final_chain
            .0
            .pbft_dpos_eligible_vote_count(request.period, request.address)
        {
            Ok(Some(vote_count)) => (
                PBFT_FINAL_CHAIN_FACT_STATUS_READY,
                vote_count,
                String::new(),
            ),
            Ok(None) => (
                PBFT_FINAL_CHAIN_FACT_STATUS_UNAVAILABLE,
                0,
                "PBFT_FINAL_CHAIN_ADDRESS_FACT_FUTURE_PERIOD".to_string(),
            ),
            Err(err) => (
                PBFT_FINAL_CHAIN_FACT_STATUS_UNAVAILABLE,
                0,
                format!("PBFT_FINAL_CHAIN_ADDRESS_FACT_UNAVAILABLE: {err}"),
            ),
        };

        Ok(FfiPbftFinalChainDposWalletEligibilityFacts {
            status,
            last_block_number,
            address: request.address,
            eligible: vote_count > 0,
            vote_count,
            error_code,
        })
    }

    /// Queries PBFT-facing per-wallet DPoS vote facts for multiple addresses.
    ///
    /// Each entry preserves request order and carries per-wallet status so PBFT
    /// callers can distinguish future snapshots and infrastructure failures.
    pub fn pbft_service_collect_dpos_wallet_eligibility_batch(
        &self,
        final_chain: &BridgeFinalChain,
        request: FfiPbftFinalChainDposWalletEligibilityBatchRequest,
    ) -> Result<FfiPbftFinalChainDposWalletEligibilityBatchFacts> {
        let last_block_number = final_chain.0.last_block_number()?;
        let mut address_facts = Vec::with_capacity(request.addresses.len());
        let mut all_ready = true;
        let mut error_code = String::new();

        for address in request.addresses {
            let (status, vote_count, address_error_code) = match final_chain
                .0
                .pbft_dpos_eligible_vote_count(request.period, address.address)
            {
                Ok(Some(vote_count)) => (
                    PBFT_FINAL_CHAIN_FACT_STATUS_READY,
                    vote_count,
                    String::new(),
                ),
                Ok(None) => (
                    PBFT_FINAL_CHAIN_FACT_STATUS_UNAVAILABLE,
                    0,
                    "PBFT_FINAL_CHAIN_ADDRESS_FACT_FUTURE_PERIOD".to_string(),
                ),
                Err(err) => (
                    PBFT_FINAL_CHAIN_FACT_STATUS_UNAVAILABLE,
                    0,
                    format!("PBFT_FINAL_CHAIN_ADDRESS_FACT_UNAVAILABLE: {err}"),
                ),
            };

            if status != PBFT_FINAL_CHAIN_FACT_STATUS_READY {
                all_ready = false;
                if error_code.is_empty() {
                    error_code = address_error_code.clone();
                }
            }

            address_facts.push(FfiPbftFinalChainDposAddressVoteFact {
                address: address.address,
                status,
                eligible: vote_count > 0,
                vote_count,
                error_code: address_error_code,
            });
        }

        let status = if all_ready {
            PBFT_FINAL_CHAIN_FACT_STATUS_READY
        } else {
            PBFT_FINAL_CHAIN_FACT_STATUS_UNAVAILABLE
        };
        let error_code = if status == PBFT_FINAL_CHAIN_FACT_STATUS_READY {
            String::new()
        } else if error_code.is_empty() {
            "PBFT_FINAL_CHAIN_ADDRESS_FACTS_UNAVAILABLE".to_string()
        } else {
            error_code
        };

        Ok(FfiPbftFinalChainDposWalletEligibilityBatchFacts {
            status,
            last_block_number,
            address_facts,
            error_code,
        })
    }
}

impl TryFrom<FfiPbftVoteGenerationInput> for PbftVoteGenerationInput {
    type Error = anyhow::Error;

    fn try_from(value: FfiPbftVoteGenerationInput) -> Result<Self> {
        Ok(Self {
            block_hash: H256::from(value.block_hash),
            vote_type: PbftVoteType::try_from(value.vote_type)?,
            period: value.period,
            round: value.round,
            step: value.step,
            node_secret: value.node_secret,
            vrf_secret: value.vrf_secret,
            expected_voter: H160::from(value.expected_voter),
            expected_vrf_public_key: value.expected_vrf_public_key,
        })
    }
}

impl From<PbftGeneratedVote> for FfiPbftGeneratedVote {
    fn from(value: PbftGeneratedVote) -> Self {
        Self {
            status: value.status.as_u8(),
            error_code: value.error_code.to_owned(),
            accepted: value.accepted,
            vote_hash: value.vote_hash.into(),
            signing_hash: value.signing_hash.into(),
            block_hash: value.block_hash.into(),
            voter: value.voter.0,
            voter_public_key: value.voter_public_key,
            vrf_public_key: value.vrf_public_key,
            vrf_proof: value.vrf_proof,
            vrf_output: value.vrf_output,
            period: value.period,
            round: value.round,
            step: value.step,
            vote_type: value.vote_type.into(),
            has_weight: value.has_weight,
            weight: value.weight,
            vote_rlp: value.vote_rlp,
        }
    }
}

impl From<PbftProposerSortitionResult> for FfiPbftProposerSortitionResult {
    fn from(value: PbftProposerSortitionResult) -> Self {
        Self {
            status: value.status.as_u8(),
            error_code: value.error_code.to_owned(),
            accepted: value.accepted,
        }
    }
}

impl TryFrom<FfiPbftProposerSortitionRequest> for PbftProposerSortitionRequest {
    type Error = anyhow::Error;

    fn try_from(value: FfiPbftProposerSortitionRequest) -> Result<Self> {
        Ok(Self {
            pbft_period: value.pbft_period,
            pbft_round: value.pbft_round,
            number_of_proposers: value.number_of_proposers,
            vrf_secret: value.vrf_secret,
            expected_vrf_public_key: value.expected_vrf_public_key,
            voter_public_key: value.voter_public_key,
            expected_voter: H160::from(value.expected_voter),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ffi::rustaxa_ffi;
    use crate::final_chain::create_final_chain;
    use crate::pbft_manager::create_pbft_service_from_storage;
    use crate::storage::create_storage;
    use k256::ecdsa::SigningKey;
    use std::time::{SystemTime, UNIX_EPOCH};

    const NODE_SECRET: [u8; 32] = [0x24; 32];
    const NODE_SECRET_ZERO_STAKE: [u8; 32] = [0x55; 32];
    const VRF_SECRET: [u8; 64] = [
        0x90, 0xf5, 0x9a, 0x7e, 0xe7, 0xa3, 0x92, 0xc8, 0x11, 0xc5, 0xd2, 0x99, 0xb5, 0x57, 0xa4,
        0xe0, 0x9e, 0x61, 0x0d, 0xe7, 0xd1, 0x09, 0xd6, 0xb3, 0xfc, 0xb1, 0x9a, 0xb8, 0xd5, 0x1c,
        0x9a, 0x0d, 0x93, 0x1f, 0x5e, 0x7d, 0xb0, 0x7c, 0x99, 0x69, 0xe4, 0x38, 0xdb, 0x7e, 0x28,
        0x7e, 0xab, 0xba, 0xac, 0xa4, 0x9c, 0xa4, 0x14, 0xf5, 0xf3, 0xa4, 0x02, 0xea, 0x69, 0x97,
        0xad, 0xe4, 0x00, 0x81,
    ];

    fn voter_from_secret(secret: &[u8; 32]) -> [u8; 20] {
        let key = SigningKey::from_slice(secret).unwrap();
        let public_key = key.verifying_key().to_encoded_point(false);
        let mut output = [0_u8; 32];
        let mut hasher = tiny_keccak::Keccak::v256();
        tiny_keccak::Hasher::update(&mut hasher, &public_key.as_bytes()[1..]);
        tiny_keccak::Hasher::finalize(hasher, &mut output);
        output[12..].try_into().unwrap()
    }

    fn test_fixture() -> (
        Box<crate::ffi::BridgePbftService>,
        Box<crate::ffi::BridgeFinalChain>,
    ) {
        let mut path = std::env::temp_dir();
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time")
            .as_nanos();
        path.push(format!("rustaxa_bridge_pbft_vote_generation_{nanos}"));

        let storage = create_storage(path.to_str().expect("temp path")).unwrap();
        let service = create_pbft_service_from_storage(
            &storage,
            rustaxa_ffi::PbftServiceConfig {
                genesis_lambda_ms: 100,
                cacti_lambda_max_ms: 1500,
                cacti_lambda_default_ms: 500,
                cacti_block: 1,
                max_exponential_lambda_ms: 60_000,
                max_steps: 13,
                deadline_ms: 1000,
                polling_interval_ms: 100,
                report_malicious_behaviour: true,
                magnolia_activation_period: 0,
            },
        )
        .unwrap();

        let final_chain = create_final_chain(
            &storage,
            0,
            0,
            Vec::new(),
            vec![rustaxa_ffi::GenesisValidator {
                address: voter_from_secret(&NODE_SECRET),
                owner: voter_from_secret(&NODE_SECRET),
                vrf_key: rustaxa_vdf::vrf::public_key_from_secret(&VRF_SECRET).unwrap(),
                commission: 0,
                description: String::new(),
                endpoint: String::new(),
                total_stake: u256_be(5_000),
                delegations: vec![rustaxa_ffi::GenesisDelegation {
                    delegator: voter_from_secret(&NODE_SECRET),
                    stake: u256_be(5_000),
                }],
            }],
            rustaxa_ffi::GenesisDposConfig {
                eligibility_balance_threshold: u256_be(1_000),
                vote_eligibility_balance_step: u256_be(1_000),
                validator_maximum_stake: u256_be(30_000),
                minimum_deposit: Vec::new(),
                commission_change_delta: 0,
                commission_change_frequency: 0,
                delegation_delay: 0,
                dag_vdf_sortition_total_vote_count_until_period: 0,
            },
        )
        .unwrap();

        (service, final_chain)
    }

    fn u256_be(value: u64) -> Vec<u8> {
        let bytes = ethereum_types::U256::from(value).to_big_endian();
        let mut padded = [0_u8; 32];
        padded[32 - bytes.len()..].copy_from_slice(&bytes);
        padded.to_vec()
    }

    fn input(vote_type: u8, step: u64, secret: [u8; 32]) -> FfiPbftVoteGenerationInput {
        FfiPbftVoteGenerationInput {
            block_hash: [0x11; 32],
            vote_type,
            period: 9,
            round: 1,
            step,
            node_secret: secret,
            vrf_secret: VRF_SECRET,
            expected_voter: voter_from_secret(&secret),
            expected_vrf_public_key: rustaxa_vdf::vrf::public_key_from_secret(&VRF_SECRET).unwrap(),
        }
    }

    fn input_with_period(
        vote_type: u8,
        step: u64,
        secret: [u8; 32],
        period: u64,
    ) -> FfiPbftVoteGenerationInput {
        FfiPbftVoteGenerationInput {
            block_hash: [0x11; 32],
            vote_type,
            period,
            round: 1,
            step,
            node_secret: secret,
            vrf_secret: VRF_SECRET,
            expected_voter: voter_from_secret(&secret),
            expected_vrf_public_key: rustaxa_vdf::vrf::public_key_from_secret(&VRF_SECRET).unwrap(),
        }
    }

    fn proposer_sortition_request(
        voter_secret: [u8; 32],
        pbft_period: u64,
        pbft_round: u64,
        number_of_proposers: u64,
    ) -> FfiPbftProposerSortitionRequest {
        let expected_voter = voter_from_secret(&voter_secret);
        let signing_key = SigningKey::from_slice(&voter_secret).unwrap();
        let point = signing_key.verifying_key().to_encoded_point(false);
        let mut voter_public_key = [0_u8; 64];
        voter_public_key.copy_from_slice(&point.as_bytes()[1..]);

        FfiPbftProposerSortitionRequest {
            pbft_period,
            pbft_round,
            number_of_proposers,
            vrf_secret: VRF_SECRET,
            expected_vrf_public_key: rustaxa_vdf::vrf::public_key_from_secret(&VRF_SECRET).unwrap(),
            voter_public_key,
            expected_voter,
        }
    }

    #[test]
    fn bridge_service_generates_and_validates_local_proposer_sortition() {
        let (service, final_chain) = test_fixture();
        let request = proposer_sortition_request(NODE_SECRET, 1, 1, 100);

        let result = service
            .pbft_service_generate_and_validate_proposer_sortition(&final_chain, request)
            .unwrap();

        assert_eq!(
            result.status,
            rustaxa_consensus::pbft_vote_validation::PbftProposerSortitionStatus::Valid.as_u8()
        );
        assert!(result.accepted);
        assert_eq!(result.error_code, "");
    }

    #[test]
    fn bridge_service_proposer_sortition_is_deterministic_for_identical_inputs() {
        let (service, final_chain) = test_fixture();
        let request = proposer_sortition_request(NODE_SECRET, 1, 1, 100);

        let first = service
            .pbft_service_generate_and_validate_proposer_sortition(&final_chain, request)
            .unwrap();
        let second = service
            .pbft_service_generate_and_validate_proposer_sortition(
                &final_chain,
                proposer_sortition_request(NODE_SECRET, 1, 1, 100),
            )
            .unwrap();

        assert_eq!(first.status, second.status);
        assert_eq!(first.accepted, second.accepted);
        assert_eq!(first.error_code, second.error_code);
    }

    #[test]
    fn bridge_service_reports_proposer_sortition_zero_stake_as_typed_status() {
        let (service, final_chain) = test_fixture();
        let request = proposer_sortition_request(NODE_SECRET_ZERO_STAKE, 1, 1, 100);

        let result = service
            .pbft_service_generate_and_validate_proposer_sortition(&final_chain, request)
            .unwrap();

        assert_eq!(
            result.status,
            rustaxa_consensus::pbft_vote_validation::PbftProposerSortitionStatus::ZeroStake.as_u8()
        );
        assert!(!result.accepted);
    }

    #[test]
    fn bridge_service_reports_proposer_sortition_future_as_typed_status() {
        let (service, final_chain) = test_fixture();
        let request = proposer_sortition_request(NODE_SECRET, 99, 1, 100);

        let result = service
            .pbft_service_generate_and_validate_proposer_sortition(&final_chain, request)
            .unwrap();

        assert_eq!(
            result.status,
            rustaxa_consensus::pbft_vote_validation::PbftProposerSortitionStatus::FutureDposState
                .as_u8()
        );
    }

    #[test]
    fn bridge_service_errors_on_proposer_sortition_period_zero() {
        let (service, final_chain) = test_fixture();
        let request = proposer_sortition_request(NODE_SECRET, 0, 1, 100);

        let err = service
            .pbft_service_generate_and_validate_proposer_sortition(&final_chain, request)
            .expect_err("period 0 must underflow");
        assert!(err
            .to_string()
            .contains("PBFT_PROPOSER_SORTITION_PERIOD_UNDERFLOW"));
    }

    #[test]
    fn bridge_service_errors_on_proposer_sortition_identity_mismatch() {
        let (service, final_chain) = test_fixture();
        let mut request = proposer_sortition_request(NODE_SECRET, 1, 1, 100);
        request.expected_voter = voter_from_secret(&NODE_SECRET_ZERO_STAKE);

        let err = service
            .pbft_service_generate_and_validate_proposer_sortition(&final_chain, request)
            .expect_err("identity mismatch must be a boundary error");
        assert!(err
            .to_string()
            .contains("PBFT_PROPOSER_SORTITION_INVALID_VOTER_IDENTITY"));
    }

    #[test]
    fn bridge_service_validates_proposer_sortition_identity_before_future_period_lookup() {
        let (service, final_chain) = test_fixture();
        let mut request = proposer_sortition_request(NODE_SECRET, 99, 1, 100);
        request.expected_voter = voter_from_secret(&NODE_SECRET_ZERO_STAKE);

        let err = service
            .pbft_service_generate_and_validate_proposer_sortition(&final_chain, request)
            .expect_err("identity mismatch must be checked before FinalChain state");
        assert!(err
            .to_string()
            .contains("PBFT_PROPOSER_SORTITION_INVALID_VOTER_IDENTITY"));
    }

    #[test]
    fn bridge_service_validates_proposer_sortition_vrf_public_key_before_future_period_lookup() {
        let (service, final_chain) = test_fixture();
        let mut request = proposer_sortition_request(NODE_SECRET, 99, 1, 100);
        request.expected_vrf_public_key = [0_u8; 32];

        let err = service
            .pbft_service_generate_and_validate_proposer_sortition(&final_chain, request)
            .expect_err("vrf mismatch must be checked before FinalChain state");
        assert!(err
            .to_string()
            .contains("PBFT_PROPOSER_SORTITION_INVALID_VRF_PUBLIC_KEY"));
    }

    #[test]
    fn bridge_service_errors_on_proposer_sortition_vrf_mismatch() {
        let (service, final_chain) = test_fixture();
        let mut request = proposer_sortition_request(NODE_SECRET, 1, 1, 100);
        request.expected_vrf_public_key = [0_u8; 32];

        let err = service
            .pbft_service_generate_and_validate_proposer_sortition(&final_chain, request)
            .expect_err("vrf public key mismatch must be a boundary error");
        assert!(err
            .to_string()
            .contains("PBFT_PROPOSER_SORTITION_INVALID_VRF_PUBLIC_KEY"));
    }

    #[test]
    fn bridge_generates_signed_vote_bytes() {
        let vote = pbft_generate_signed_vote(input(3, 3, NODE_SECRET)).unwrap();
        assert!(vote.accepted);
        assert!(!vote.has_weight);
        assert_eq!(vote.vote_type, 3);
        assert!(!vote.vote_rlp.is_empty());
    }

    #[test]
    fn bridge_service_generates_weighted_vote_bytes() {
        let (service, final_chain) = test_fixture();
        let vote = service
            .pbft_service_generate_signed_vote_with_weight(
                &final_chain,
                input_with_period(1, 1, NODE_SECRET, 1),
                50,
                100,
            )
            .unwrap();
        assert!(vote.accepted);
        assert!(vote.has_weight);
        assert!(vote.weight > 0);
    }

    #[test]
    fn bridge_service_generates_weighted_zero_stake_vote() {
        let (service, final_chain) = test_fixture();
        let vote = service
            .pbft_service_generate_signed_vote_with_weight(
                &final_chain,
                input_with_period(1, 1, NODE_SECRET_ZERO_STAKE, 1),
                50,
                100,
            )
            .unwrap();
        assert_eq!(
            vote.status,
            rustaxa_consensus::pbft_vote_generation::PbftVoteGenerationStatus::ZeroStake.as_u8()
        );
        assert!(!vote.accepted);
    }

    #[test]
    fn bridge_service_reports_zero_weight_as_typed_generation_status() {
        let (service, final_chain) = test_fixture();
        let vote = service
            .pbft_service_generate_signed_vote_with_weight(
                &final_chain,
                input_with_period(1, 1, NODE_SECRET, 1),
                0,
                0,
            )
            .unwrap();
        assert_eq!(
            vote.status,
            rustaxa_consensus::pbft_vote_generation::PbftVoteGenerationStatus::ZeroWeight.as_u8()
        );
        assert!(!vote.accepted);
    }

    #[test]
    fn bridge_service_preserves_identity_error_before_zero_stake_status() {
        let (service, final_chain) = test_fixture();
        let mut mismatched = input_with_period(1, 1, NODE_SECRET, 1);
        mismatched.expected_voter = voter_from_secret(&NODE_SECRET_ZERO_STAKE);
        let vote = service
            .pbft_service_generate_signed_vote_with_weight(&final_chain, mismatched, 50, 100)
            .unwrap();
        assert_eq!(
            vote.status,
            rustaxa_consensus::pbft_vote_generation::PbftVoteGenerationStatus::NodeSecretMismatch
                .as_u8()
        );
        assert!(!vote.accepted);
    }

    #[test]
    fn bridge_service_generates_weighted_vote_from_future_period() {
        let (service, final_chain) = test_fixture();
        assert!(service
            .pbft_service_generate_signed_vote_with_weight(
                &final_chain,
                input_with_period(1, 1, NODE_SECRET, 99),
                50,
                100
            )
            .is_err());
    }

    #[test]
    fn bridge_service_generates_weighted_vote_from_period_zero() {
        let (service, final_chain) = test_fixture();
        assert!(service
            .pbft_service_generate_signed_vote_with_weight(
                &final_chain,
                input_with_period(1, 1, NODE_SECRET, 0),
                50,
                100
            )
            .is_err());
    }

    #[test]
    fn bridge_service_rejects_invalid_weighted_vote_type() {
        let (service, final_chain) = test_fixture();
        let invalid_input = input_with_period(255, 1, NODE_SECRET, 1);
        assert!(service
            .pbft_service_generate_signed_vote_with_weight(&final_chain, invalid_input, 50, 100)
            .is_err());
    }

    #[test]
    fn bridge_service_collects_pbft_dpos_total_vote_count() {
        let (service, final_chain) = test_fixture();
        let ready = service
            .pbft_service_collect_dpos_total_vote_count(
                &final_chain,
                rustaxa_ffi::PbftFinalChainDposTotalVoteCountRequest { period: 0 },
            )
            .expect("ready total-vote lookup should return data");
        assert_eq!(ready.status, 0);
        assert!(ready.has_total_vote_count);
        assert_eq!(ready.total_vote_count, 5);

        let future = service
            .pbft_service_collect_dpos_total_vote_count(
                &final_chain,
                rustaxa_ffi::PbftFinalChainDposTotalVoteCountRequest { period: 99 },
            )
            .expect("future total-vote lookup should be returned as unavailable data");
        assert_eq!(future.status, 1);
        assert!(!future.has_total_vote_count);
        assert_eq!(
            future.error_code,
            "PBFT_FINAL_CHAIN_TOTAL_VOTES_FUTURE_PERIOD"
        );
    }

    #[test]
    fn bridge_service_collects_pbft_dpos_wallet_aggregate_vote_count() {
        let (service, final_chain) = test_fixture();
        let validator = voter_from_secret(&NODE_SECRET);
        let ready = service
            .pbft_service_collect_dpos_wallet_aggregate_vote_count(
                &final_chain,
                rustaxa_ffi::PbftFinalChainDposWalletAggregateVoteCountRequest {
                    period: 0,
                    addresses: vec![
                        rustaxa_ffi::PbftFinalChainDposAddress { address: validator },
                        rustaxa_ffi::PbftFinalChainDposAddress {
                            address: [0xA1; 20],
                        },
                    ],
                },
            )
            .expect("ready aggregate vote lookup should return data");
        assert_eq!(ready.status, 0);
        assert!(ready.has_aggregate_vote_count);
        assert_eq!(ready.aggregate_vote_count, 5);

        let unavailable = service
            .pbft_service_collect_dpos_wallet_aggregate_vote_count(
                &final_chain,
                rustaxa_ffi::PbftFinalChainDposWalletAggregateVoteCountRequest {
                    period: 99,
                    addresses: vec![rustaxa_ffi::PbftFinalChainDposAddress { address: validator }],
                },
            )
            .expect("future aggregate vote lookup should be returned as unavailable data");
        assert_eq!(unavailable.status, 1);
        assert!(!unavailable.has_aggregate_vote_count);
        assert_eq!(
            unavailable.error_code,
            "PBFT_FINAL_CHAIN_WALLET_VOTES_FUTURE_PERIOD"
        );
    }

    #[test]
    fn bridge_service_collects_pbft_dpos_wallet_eligibility() {
        let (service, final_chain) = test_fixture();
        let validator = voter_from_secret(&NODE_SECRET);
        let ready = service
            .pbft_service_collect_dpos_wallet_eligibility(
                &final_chain,
                rustaxa_ffi::PbftFinalChainDposWalletEligibilityRequest {
                    period: 0,
                    address: validator,
                },
            )
            .expect("ready wallet eligibility lookup should return data");
        assert_eq!(ready.status, 0);
        assert!(ready.eligible);
        assert_eq!(ready.vote_count, 5);

        let zero_stake = service
            .pbft_service_collect_dpos_wallet_eligibility(
                &final_chain,
                rustaxa_ffi::PbftFinalChainDposWalletEligibilityRequest {
                    period: 0,
                    address: [0xA1; 20],
                },
            )
            .expect("zero-stake wallet lookup should be ready with zero values");
        assert_eq!(zero_stake.status, 0);
        assert!(!zero_stake.eligible);
        assert_eq!(zero_stake.vote_count, 0);
    }

    #[test]
    fn bridge_service_collects_pbft_dpos_wallet_eligibility_batch() {
        let (service, final_chain) = test_fixture();
        let validator = voter_from_secret(&NODE_SECRET);
        let ready = service
            .pbft_service_collect_dpos_wallet_eligibility_batch(
                &final_chain,
                rustaxa_ffi::PbftFinalChainDposWalletEligibilityBatchRequest {
                    period: 0,
                    addresses: vec![
                        rustaxa_ffi::PbftFinalChainDposAddress { address: validator },
                        rustaxa_ffi::PbftFinalChainDposAddress {
                            address: [0xA1; 20],
                        },
                    ],
                },
            )
            .expect("ready wallet batch lookup should return data");
        assert_eq!(ready.status, 0);
        assert_eq!(ready.address_facts.len(), 2);
        assert_eq!(ready.address_facts[0].status, 0);
        assert_eq!(ready.address_facts[1].status, 0);
        assert_eq!(ready.address_facts[0].vote_count, 5);
        assert_eq!(ready.address_facts[1].vote_count, 0);

        let unavailable = service
            .pbft_service_collect_dpos_wallet_eligibility_batch(
                &final_chain,
                rustaxa_ffi::PbftFinalChainDposWalletEligibilityBatchRequest {
                    period: 99,
                    addresses: vec![
                        rustaxa_ffi::PbftFinalChainDposAddress { address: validator },
                        rustaxa_ffi::PbftFinalChainDposAddress {
                            address: [0xA1; 20],
                        },
                    ],
                },
            )
            .expect("future batch lookup should be returned as unavailable data");
        assert_eq!(unavailable.status, 1);
        assert_eq!(unavailable.address_facts[0].status, 1);
        assert_eq!(
            unavailable.address_facts[0].error_code,
            "PBFT_FINAL_CHAIN_ADDRESS_FACT_FUTURE_PERIOD"
        );
    }
}
