//! CXX bridge wrappers for Rust PBFT vote generation.
//!
//! The bridge exposes a byte-oriented generation contract to the C++
//! `VoteManager` shim. Rust composes weighted generation with borrowed
//! FinalChain state; C++ retains wallet selection and temporary live `PbftVote`
//! materialization from canonical Rust-generated bytes.

use crate::ffi::rustaxa_ffi::{
    PbftFinalChainDposAddressVoteFact as FfiPbftFinalChainDposAddressVoteFact,
    PbftFinalChainDposTotalVoteCountFacts as FfiPbftFinalChainDposTotalVoteCountFacts,
    PbftFinalChainDposTotalVoteCountRequest as FfiPbftFinalChainDposTotalVoteCountRequest,
    PbftFinalChainDposWalletAggregateVoteCountFacts as FfiPbftFinalChainDposWalletAggregateVoteCountFacts,
    PbftFinalChainDposWalletAggregateVoteCountRequest as FfiPbftFinalChainDposWalletAggregateVoteCountRequest,
    PbftFinalChainDposWalletEligibilityBatchFacts as FfiPbftFinalChainDposWalletEligibilityBatchFacts,
    PbftFinalChainDposWalletEligibilityBatchRequest as FfiPbftFinalChainDposWalletEligibilityBatchRequest,
    PbftGeneratedVote as FfiPbftGeneratedVote,
    PbftProposerSortitionRequest as FfiPbftProposerSortitionRequest,
    PbftProposerSortitionResult as FfiPbftProposerSortitionResult,
    PbftVoteGenerationInput as FfiPbftVoteGenerationInput,
};
use crate::ffi::{BridgeApp, BridgeFinalChain};
use anyhow::Result;
use ethereum_types::{H160, H256};
use rustaxa_consensus::pbft_vote_generation::{
    generate_pbft_vote, PbftFinalChainDposAddressVoteFact, PbftFinalChainDposTotalVoteCountFacts,
    PbftFinalChainDposTotalVoteCountRequest, PbftFinalChainDposWalletAggregateVoteCountFacts,
    PbftFinalChainDposWalletAggregateVoteCountRequest,
    PbftFinalChainDposWalletEligibilityBatchFacts, PbftFinalChainDposWalletEligibilityBatchRequest,
    PbftFinalChainFact, PbftGeneratedVote, PbftVoteGenerationInput,
};
use rustaxa_consensus::pbft_vote_validation::{
    PbftProposerSortitionRequest, PbftProposerSortitionResult,
};
use rustaxa_consensus::verified_votes::PbftVoteType;

/// Generates one signed PBFT vote payload in Rust.
pub fn pbft_generate_signed_vote(
    input: FfiPbftVoteGenerationInput,
) -> Result<FfiPbftGeneratedVote> {
    Ok(generate_pbft_vote(input.try_into()?)?.into())
}

impl BridgeApp {
    /// Generates one canonical signed and weighted PBFT vote from live Rust FinalChain state.
    ///
    /// The caller supplies wallet/signing input and immutable committee configuration. The
    /// operation converts the PBFT period to its DPoS period, reads voter stake before total
    /// stake, and delegates deterministic signing and weighting to `rustaxa-consensus`. Zero
    /// stake, zero total stake, and zero weight remain typed generation outcomes. Period
    /// underflow, future state, and unavailable/corrupt snapshots are boundary errors. No PBFT
    /// service lock or FinalChain handle is retained after the synchronous call.
    pub fn pbft_service_generate_signed_vote_with_weight(
        &self,
        final_chain: &BridgeFinalChain,
        input: FfiPbftVoteGenerationInput,
        committee_size: u64,
        number_of_proposers: u64,
    ) -> Result<FfiPbftGeneratedVote> {
        let input: PbftVoteGenerationInput = input.try_into()?;
        Ok(self
            .0
            .generate_signed_vote_with_weight(
                &final_chain.0,
                input,
                committee_size,
                number_of_proposers,
            )?
            .into())
    }

    /// Generates proposer-sortition proof inputs and validates local proposer weight.
    ///
    /// The caller supplies raw FinalChain voter identity and DPoS facts are read
    /// from `final_chain` by PBFT period semantics (`dpos_period = pbft_period - 1`).
    /// Identity and proof validation errors are returned as boundary errors.
    pub fn pbft_service_generate_and_validate_proposer_sortition(
        &self,
        final_chain: &BridgeFinalChain,
        request: FfiPbftProposerSortitionRequest,
    ) -> Result<FfiPbftProposerSortitionResult> {
        Ok(self
            .0
            .generate_and_validate_proposer_sortition(
                &final_chain.0,
                PbftProposerSortitionRequest::try_from(request)?,
            )?
            .into())
    }

    /// Queries PBFT-facing total DPoS-vote facts for an exact period.
    ///
    /// `Ok(None)` period availability is projected as
    /// `PBFT_FINAL_CHAIN_FACT_STATUS_UNAVAILABLE` with a dedicated error string.
    pub fn pbft_service_collect_dpos_total_vote_count(
        &self,
        final_chain: &BridgeFinalChain,
        request: FfiPbftFinalChainDposTotalVoteCountRequest,
    ) -> Result<FfiPbftFinalChainDposTotalVoteCountFacts> {
        Ok(self
            .0
            .collect_dpos_total_vote_count(
                &final_chain.0,
                PbftFinalChainDposTotalVoteCountRequest {
                    period: request.period,
                },
            )?
            .into())
    }

    /// Queries PBFT-facing aggregate DPoS-vote facts for a supplied wallet subset.
    ///
    /// The aggregate is the simple sum of wallet eligible vote counts. Futures and
    /// storage corruption are returned as unavailable data using typed status/error
    /// codes instead of silently returning partial totals.
    pub fn pbft_service_collect_dpos_wallet_aggregate_vote_count(
        &self,
        final_chain: &BridgeFinalChain,
        request: FfiPbftFinalChainDposWalletAggregateVoteCountRequest,
    ) -> Result<FfiPbftFinalChainDposWalletAggregateVoteCountFacts> {
        Ok(self
            .0
            .collect_dpos_wallet_aggregate_vote_count(
                &final_chain.0,
                PbftFinalChainDposWalletAggregateVoteCountRequest {
                    period: request.period,
                    eligible_wallet_period: request.eligible_wallet_period,
                    addresses: request
                        .addresses
                        .into_iter()
                        .map(|entry| H160::from(entry.address))
                        .collect(),
                },
            )?
            .into())
    }

    /// Queries PBFT-facing per-wallet DPoS vote facts for multiple addresses.
    ///
    /// Each entry preserves request order and carries per-wallet status so PBFT
    /// callers can distinguish future snapshots and infrastructure failures.
    pub fn pbft_service_collect_dpos_wallet_eligibility_batch(
        &self,
        final_chain: &BridgeFinalChain,
        request: FfiPbftFinalChainDposWalletEligibilityBatchRequest,
    ) -> Result<FfiPbftFinalChainDposWalletEligibilityBatchFacts> {
        Ok(self
            .0
            .collect_dpos_wallet_eligibility_batch(
                &final_chain.0,
                PbftFinalChainDposWalletEligibilityBatchRequest {
                    period: request.period,
                    addresses: request
                        .addresses
                        .into_iter()
                        .map(|entry| H160::from(entry.address))
                        .collect(),
                },
            )?
            .into())
    }
}

impl TryFrom<FfiPbftVoteGenerationInput> for PbftVoteGenerationInput {
    type Error = anyhow::Error;

    fn try_from(value: FfiPbftVoteGenerationInput) -> Result<Self> {
        Ok(Self {
            block_hash: H256::from(value.block_hash),
            vote_type: PbftVoteType::try_from(value.vote_type)?,
            period: value.period,
            round: value.round,
            step: value.step,
            node_secret: value.node_secret,
            vrf_secret: value.vrf_secret,
            expected_voter: H160::from(value.expected_voter),
            expected_vrf_public_key: value.expected_vrf_public_key,
        })
    }
}

impl From<PbftGeneratedVote> for FfiPbftGeneratedVote {
    fn from(value: PbftGeneratedVote) -> Self {
        Self {
            status: value.status.as_u8(),
            error_code: value.error_code.to_owned(),
            accepted: value.accepted,
            vote_hash: value.vote_hash.into(),
            block_hash: value.block_hash.into(),
            voter: value.voter.0,
            voter_public_key: value.voter_public_key,
            vrf_public_key: value.vrf_public_key,
            vrf_proof: value.vrf_proof,
            vrf_output: value.vrf_output,
            period: value.period,
            round: value.round,
            step: value.step,
            vote_type: value.vote_type.into(),
            has_weight: value.has_weight,
            weight: value.weight,
            vote_rlp: value.vote_rlp,
        }
    }
}

impl From<PbftFinalChainDposAddressVoteFact> for FfiPbftFinalChainDposAddressVoteFact {
    fn from(value: PbftFinalChainDposAddressVoteFact) -> Self {
        let status = value.status;
        let status_code = status.as_u8();
        let (eligible, vote_count, error_code) = match status {
            PbftFinalChainFact::Ready(vote_count) => (vote_count > 0, vote_count, String::new()),
            PbftFinalChainFact::Unavailable { error_code } => (false, 0, error_code),
        };

        Self {
            address: value.address.0,
            status: status_code,
            eligible,
            vote_count,
            error_code,
        }
    }
}

impl From<PbftFinalChainDposTotalVoteCountFacts> for FfiPbftFinalChainDposTotalVoteCountFacts {
    fn from(value: PbftFinalChainDposTotalVoteCountFacts) -> Self {
        let status = value.status;
        let status_code = status.as_u8();
        let (has_total_vote_count, total_vote_count, error_code) = match status {
            PbftFinalChainFact::Ready(total_vote_count) => (true, total_vote_count, String::new()),
            PbftFinalChainFact::Unavailable { error_code } => (false, 0, error_code),
        };

        Self {
            status: status_code,
            last_block_number: value.last_block_number.as_u64(),
            has_total_vote_count,
            total_vote_count,
            error_code,
        }
    }
}

impl From<PbftFinalChainDposWalletAggregateVoteCountFacts>
    for FfiPbftFinalChainDposWalletAggregateVoteCountFacts
{
    fn from(value: PbftFinalChainDposWalletAggregateVoteCountFacts) -> Self {
        let status = value.status;
        let status_code = status.as_u8();
        let (has_aggregate_vote_count, aggregate_vote_count, error_code) = match status {
            PbftFinalChainFact::Ready(aggregate_vote_count) => {
                (true, aggregate_vote_count, String::new())
            }
            PbftFinalChainFact::Unavailable { error_code } => (false, 0, error_code),
        };

        Self {
            status: status_code,
            last_block_number: value.last_block_number.as_u64(),
            has_aggregate_vote_count,
            aggregate_vote_count,
            eligible_wallet_period_ready: value.eligible_wallet_period_ready,
            error_code,
        }
    }
}

impl From<PbftFinalChainDposWalletEligibilityBatchFacts>
    for FfiPbftFinalChainDposWalletEligibilityBatchFacts
{
    fn from(value: PbftFinalChainDposWalletEligibilityBatchFacts) -> Self {
        let status_code = value.status.as_u8();
        let error_code = value.status.error_code().to_owned();

        Self {
            status: status_code,
            last_block_number: value.last_block_number.as_u64(),
            address_facts: value
                .address_facts
                .into_iter()
                .map(FfiPbftFinalChainDposAddressVoteFact::from)
                .collect(),
            error_code,
        }
    }
}

impl From<PbftProposerSortitionResult> for FfiPbftProposerSortitionResult {
    fn from(value: PbftProposerSortitionResult) -> Self {
        Self {
            status: value.status.as_u8(),
            error_code: value.error_code.to_owned(),
            accepted: value.accepted,
        }
    }
}

impl TryFrom<FfiPbftProposerSortitionRequest> for PbftProposerSortitionRequest {
    type Error = anyhow::Error;

    fn try_from(value: FfiPbftProposerSortitionRequest) -> Result<Self> {
        Ok(Self {
            pbft_period: value.pbft_period,
            pbft_round: value.pbft_round,
            number_of_proposers: value.number_of_proposers,
            vrf_secret: value.vrf_secret,
            expected_vrf_public_key: value.expected_vrf_public_key,
            voter_public_key: value.voter_public_key,
            expected_voter: H160::from(value.expected_voter),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use k256::ecdsa::SigningKey;
    use rustaxa_consensus::pbft_vote_generation::PbftFinalChainFact;
    use rustaxa_types::FinalChainBlockNumber;
    use tiny_keccak::{Hasher, Keccak};

    const NODE_SECRET: [u8; 32] = [0x24; 32];
    const VRF_SECRET: [u8; 64] = [
        0x90, 0xf5, 0x9a, 0x7e, 0xe7, 0xa3, 0x92, 0xc8, 0x11, 0xc5, 0xd2, 0x99, 0xb5, 0x57, 0xa4,
        0xe0, 0x9e, 0x61, 0x0d, 0xe7, 0xd1, 0x09, 0xd6, 0xb3, 0xfc, 0xb1, 0x9a, 0xb8, 0xd5, 0x1c,
        0x9a, 0x0d, 0x93, 0x1f, 0x5e, 0x7d, 0xb0, 0x7c, 0x99, 0x69, 0xe4, 0x38, 0xdb, 0x7e, 0x28,
        0x7e, 0xab, 0xba, 0xac, 0xa4, 0x9c, 0xa4, 0x14, 0xf5, 0xf3, 0xa4, 0x02, 0xea, 0x69, 0x97,
        0xad, 0xe4, 0x00, 0x81,
    ];

    fn voter_from_secret(secret: &[u8; 32]) -> [u8; 20] {
        let key = SigningKey::from_slice(secret).unwrap();
        let public_key = key.verifying_key().to_encoded_point(false);
        let mut output = [0_u8; 32];
        let mut hasher = Keccak::v256();
        hasher.update(&public_key.as_bytes()[1..]);
        hasher.finalize(&mut output);
        output[12..].try_into().unwrap()
    }

    fn input(vote_type: u8, step: u64, secret: [u8; 32]) -> FfiPbftVoteGenerationInput {
        FfiPbftVoteGenerationInput {
            block_hash: [0x11; 32],
            vote_type,
            period: 9,
            round: 1,
            step,
            node_secret: secret,
            vrf_secret: VRF_SECRET,
            expected_voter: voter_from_secret(&secret),
            expected_vrf_public_key: rustaxa_vdf::vrf::public_key_from_secret(&VRF_SECRET).unwrap(),
        }
    }

    #[test]
    fn bridge_generates_signed_vote_bytes() {
        let vote = pbft_generate_signed_vote(input(3, 3, NODE_SECRET)).unwrap();
        assert!(vote.accepted);
        assert!(!vote.has_weight);
        assert_eq!(vote.vote_type, 3);
        assert!(!vote.vote_rlp.is_empty());
    }

    #[test]
    fn bridge_rejects_unknown_vote_type_at_ffi_boundary() {
        assert!(pbft_generate_signed_vote(input(u8::MAX, 3, NODE_SECRET)).is_err());
    }

    #[test]
    fn bridge_converts_ready_and_unavailable_dpos_facts() {
        let total_ready: FfiPbftFinalChainDposTotalVoteCountFacts =
            rustaxa_consensus::pbft_vote_generation::PbftFinalChainDposTotalVoteCountFacts {
                last_block_number: FinalChainBlockNumber::new(10),
                status: PbftFinalChainFact::Ready(5),
            }
            .into();

        assert_eq!(total_ready.status, 0);
        assert!(total_ready.has_total_vote_count);
        assert_eq!(total_ready.total_vote_count, 5);
        assert_eq!(total_ready.last_block_number, 10);
        assert_eq!(total_ready.error_code, "");

        let total_unavailable: FfiPbftFinalChainDposTotalVoteCountFacts =
            rustaxa_consensus::pbft_vote_generation::PbftFinalChainDposTotalVoteCountFacts {
                last_block_number: FinalChainBlockNumber::new(10),
                status: PbftFinalChainFact::Unavailable {
                    error_code: "PBFT_FINAL_CHAIN_TOTAL_VOTES_UNAVAILABLE".to_string(),
                },
            }
            .into();

        assert_eq!(total_unavailable.status, 1);
        assert!(!total_unavailable.has_total_vote_count);
        assert_eq!(
            total_unavailable.error_code,
            "PBFT_FINAL_CHAIN_TOTAL_VOTES_UNAVAILABLE"
        );
        assert_eq!(total_unavailable.total_vote_count, 0);

        let aggregate_ready: FfiPbftFinalChainDposWalletAggregateVoteCountFacts =
            rustaxa_consensus::pbft_vote_generation::PbftFinalChainDposWalletAggregateVoteCountFacts {
                last_block_number: FinalChainBlockNumber::new(5),
                status: PbftFinalChainFact::Ready(11),
                eligible_wallet_period_ready: true,
            }
            .into();

        assert_eq!(aggregate_ready.status, 0);
        assert!(aggregate_ready.eligible_wallet_period_ready);
        assert_eq!(aggregate_ready.aggregate_vote_count, 11);
        assert_eq!(aggregate_ready.error_code, "");

        let aggregate_unavailable: FfiPbftFinalChainDposWalletAggregateVoteCountFacts =
            rustaxa_consensus::pbft_vote_generation::PbftFinalChainDposWalletAggregateVoteCountFacts {
                last_block_number: FinalChainBlockNumber::new(5),
                status: PbftFinalChainFact::Unavailable {
                    error_code: "PBFT_FINAL_CHAIN_WALLET_AGGREGATE_PERIOD_MISMATCH".to_string(),
                },
                eligible_wallet_period_ready: false,
            }
            .into();

        assert_eq!(aggregate_unavailable.status, 1);
        assert!(!aggregate_unavailable.eligible_wallet_period_ready);
        assert_eq!(aggregate_unavailable.aggregate_vote_count, 0);
        assert_eq!(
            aggregate_unavailable.error_code,
            "PBFT_FINAL_CHAIN_WALLET_AGGREGATE_PERIOD_MISMATCH"
        );
    }

    #[test]
    fn bridge_conversion_preserves_batch_order_and_top_status_error_code() {
        let address_one = [0x11_u8; 20];
        let address_two = [0x22_u8; 20];
        let batch: FfiPbftFinalChainDposWalletEligibilityBatchFacts =
            rustaxa_consensus::pbft_vote_generation::PbftFinalChainDposWalletEligibilityBatchFacts {
                last_block_number: FinalChainBlockNumber::new(99),
                status: PbftFinalChainFact::Unavailable {
                    error_code: "PBFT_FINAL_CHAIN_ADDRESS_FACTS_UNAVAILABLE".to_string(),
                },
                address_facts: vec![
                    rustaxa_consensus::pbft_vote_generation::PbftFinalChainDposAddressVoteFact {
                        address: address_one.into(),
                        status: PbftFinalChainFact::Ready(5),
                    },
                    rustaxa_consensus::pbft_vote_generation::PbftFinalChainDposAddressVoteFact {
                        address: address_two.into(),
                        status: PbftFinalChainFact::Unavailable {
                            error_code: "PBFT_FINAL_CHAIN_ADDRESS_FACT_FUTURE_PERIOD".to_string(),
                        },
                    },
                    rustaxa_consensus::pbft_vote_generation::PbftFinalChainDposAddressVoteFact {
                        address: address_one.into(),
                        status: PbftFinalChainFact::Ready(0),
                    },
                ],
            }
            .into();

        assert_eq!(batch.status, 1);
        assert_eq!(
            batch.error_code,
            "PBFT_FINAL_CHAIN_ADDRESS_FACTS_UNAVAILABLE"
        );
        assert_eq!(batch.address_facts.len(), 3);
        assert_eq!(batch.address_facts[0].address, address_one);
        assert_eq!(batch.address_facts[1].address, address_two);
        assert_eq!(batch.address_facts[2].address, address_one);
        assert_eq!(batch.address_facts[0].status, 0);
        assert!(batch.address_facts[0].eligible);
        assert_eq!(batch.address_facts[1].status, 1);
        assert!(!batch.address_facts[1].eligible);
        assert_eq!(batch.address_facts[1].vote_count, 0);
        assert_eq!(
            batch.address_facts[1].error_code,
            "PBFT_FINAL_CHAIN_ADDRESS_FACT_FUTURE_PERIOD"
        );
        assert_eq!(batch.address_facts[2].status, 0);
        assert!(!batch.address_facts[2].eligible);
        assert_eq!(batch.address_facts[2].vote_count, 0);
    }
}
