//! CXX bridge wrappers for Rust PBFT vote generation.
//!
//! The bridge exposes a byte-oriented generation contract to the C++
//! `VoteManager` shim. Rust composes weighted generation with borrowed
//! FinalChain state; C++ retains wallet selection and temporary live `PbftVote`
//! materialization from canonical Rust-generated bytes.

use crate::ffi::rustaxa_ffi::{
    PbftGeneratedVote as FfiPbftGeneratedVote,
    PbftVoteGenerationInput as FfiPbftVoteGenerationInput,
};
use crate::ffi::{BridgeFinalChain, BridgePbftService};
use anyhow::{anyhow, Result};
use ethereum_types::{H160, H256};
use rustaxa_consensus::pbft_vote_generation::{
    generate_pbft_vote, generate_pbft_vote_with_weight, PbftGeneratedVote, PbftVoteGenerationInput,
    PbftVoteWeightFacts,
};
use rustaxa_consensus::verified_votes::PbftVoteType;

/// Generates one signed PBFT vote payload in Rust.
pub fn pbft_generate_signed_vote(
    input: FfiPbftVoteGenerationInput,
) -> Result<FfiPbftGeneratedVote> {
    Ok(generate_pbft_vote(input.try_into()?)?.into())
}

impl BridgePbftService {
    /// Generates one canonical signed and weighted PBFT vote from live Rust FinalChain state.
    ///
    /// The caller supplies wallet/signing input and immutable committee configuration. The
    /// operation converts the PBFT period to its DPoS period, reads voter stake before total
    /// stake, and delegates deterministic signing and weighting to `rustaxa-consensus`. Zero
    /// stake, zero total stake, and zero weight remain typed generation outcomes. Period
    /// underflow, future state, and unavailable/corrupt snapshots are boundary errors. No PBFT
    /// service lock or FinalChain handle is retained after the synchronous call.
    pub fn pbft_service_generate_signed_vote_with_weight(
        &self,
        final_chain: &BridgeFinalChain,
        input: FfiPbftVoteGenerationInput,
        committee_size: u64,
        number_of_proposers: u64,
    ) -> Result<FfiPbftGeneratedVote> {
        let input: PbftVoteGenerationInput = input.try_into()?;
        let dpos_period = input
            .period
            .checked_sub(1)
            .ok_or_else(|| anyhow!("PBFT_VOTE_GENERATION_PERIOD_UNDERFLOW"))?;
        let voter = input.expected_voter;

        let voter_dpos_vote_count = match final_chain
            .0
            .pbft_dpos_eligible_vote_count(dpos_period, voter.0)
        {
            Ok(Some(votes)) => votes,
            Ok(None) => anyhow::bail!("PBFT_FINAL_CHAIN_ADDRESS_FACT_FUTURE_PERIOD"),
            Err(err) => anyhow::bail!("PBFT_FINAL_CHAIN_ADDRESS_FACT_UNAVAILABLE: {err}"),
        };
        if voter_dpos_vote_count == 0 {
            return Ok(generate_pbft_vote_with_weight(
                input,
                PbftVoteWeightFacts {
                    voter_dpos_vote_count,
                    total_dpos_vote_count: 0,
                    committee_size,
                    number_of_proposers,
                },
            )?
            .into());
        }
        let total_dpos_vote_count = match final_chain
            .0
            .pbft_dpos_eligible_total_vote_count(dpos_period)
        {
            Ok(Some(total)) => total,
            Ok(None) => anyhow::bail!("PBFT_FINAL_CHAIN_TOTAL_VOTES_FACT_FUTURE_PERIOD"),
            Err(err) => anyhow::bail!("PBFT_FINAL_CHAIN_TOTAL_VOTES_FACT_UNAVAILABLE: {err}"),
        };
        let facts = PbftVoteWeightFacts {
            voter_dpos_vote_count,
            total_dpos_vote_count,
            committee_size,
            number_of_proposers,
        };
        Ok(generate_pbft_vote_with_weight(input, facts)?.into())
    }
}

impl TryFrom<FfiPbftVoteGenerationInput> for PbftVoteGenerationInput {
    type Error = anyhow::Error;

    fn try_from(value: FfiPbftVoteGenerationInput) -> Result<Self> {
        Ok(Self {
            block_hash: H256::from(value.block_hash),
            vote_type: PbftVoteType::try_from(value.vote_type)?,
            period: value.period,
            round: value.round,
            step: value.step,
            node_secret: value.node_secret,
            vrf_secret: value.vrf_secret,
            expected_voter: H160::from(value.expected_voter),
            expected_vrf_public_key: value.expected_vrf_public_key,
        })
    }
}

impl From<PbftGeneratedVote> for FfiPbftGeneratedVote {
    fn from(value: PbftGeneratedVote) -> Self {
        Self {
            status: value.status.as_u8(),
            error_code: value.error_code.to_owned(),
            accepted: value.accepted,
            vote_hash: value.vote_hash.into(),
            signing_hash: value.signing_hash.into(),
            block_hash: value.block_hash.into(),
            voter: value.voter.0,
            voter_public_key: value.voter_public_key,
            vrf_public_key: value.vrf_public_key,
            vrf_proof: value.vrf_proof,
            vrf_output: value.vrf_output,
            period: value.period,
            round: value.round,
            step: value.step,
            vote_type: value.vote_type.into(),
            has_weight: value.has_weight,
            weight: value.weight,
            vote_rlp: value.vote_rlp,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ffi::rustaxa_ffi;
    use crate::final_chain::create_final_chain;
    use crate::pbft_manager::create_pbft_service_from_storage;
    use crate::storage::create_storage;
    use k256::ecdsa::SigningKey;
    use std::time::{SystemTime, UNIX_EPOCH};

    const NODE_SECRET: [u8; 32] = [0x24; 32];
    const NODE_SECRET_ZERO_STAKE: [u8; 32] = [0x55; 32];
    const VRF_SECRET: [u8; 64] = [
        0x90, 0xf5, 0x9a, 0x7e, 0xe7, 0xa3, 0x92, 0xc8, 0x11, 0xc5, 0xd2, 0x99, 0xb5, 0x57, 0xa4,
        0xe0, 0x9e, 0x61, 0x0d, 0xe7, 0xd1, 0x09, 0xd6, 0xb3, 0xfc, 0xb1, 0x9a, 0xb8, 0xd5, 0x1c,
        0x9a, 0x0d, 0x93, 0x1f, 0x5e, 0x7d, 0xb0, 0x7c, 0x99, 0x69, 0xe4, 0x38, 0xdb, 0x7e, 0x28,
        0x7e, 0xab, 0xba, 0xac, 0xa4, 0x9c, 0xa4, 0x14, 0xf5, 0xf3, 0xa4, 0x02, 0xea, 0x69, 0x97,
        0xad, 0xe4, 0x00, 0x81,
    ];

    fn voter_from_secret(secret: &[u8; 32]) -> [u8; 20] {
        let key = SigningKey::from_slice(secret).unwrap();
        let public_key = key.verifying_key().to_encoded_point(false);
        let mut output = [0_u8; 32];
        let mut hasher = tiny_keccak::Keccak::v256();
        tiny_keccak::Hasher::update(&mut hasher, &public_key.as_bytes()[1..]);
        tiny_keccak::Hasher::finalize(hasher, &mut output);
        output[12..].try_into().unwrap()
    }

    fn test_fixture() -> (
        Box<crate::ffi::BridgePbftService>,
        Box<crate::ffi::BridgeFinalChain>,
    ) {
        let mut path = std::env::temp_dir();
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("time")
            .as_nanos();
        path.push(format!("rustaxa_bridge_pbft_vote_generation_{nanos}"));

        let storage = create_storage(path.to_str().expect("temp path")).unwrap();
        let service = create_pbft_service_from_storage(
            &storage,
            rustaxa_ffi::PbftServiceConfig {
                genesis_lambda_ms: 100,
                cacti_lambda_max_ms: 1500,
                cacti_lambda_default_ms: 500,
                cacti_block: 1,
                max_exponential_lambda_ms: 60_000,
                max_steps: 13,
                deadline_ms: 1000,
                polling_interval_ms: 100,
                report_malicious_behaviour: true,
                magnolia_activation_period: 0,
            },
        )
        .unwrap();

        let final_chain = create_final_chain(
            &storage,
            0,
            0,
            Vec::new(),
            vec![rustaxa_ffi::GenesisValidator {
                address: voter_from_secret(&NODE_SECRET),
                owner: voter_from_secret(&NODE_SECRET),
                vrf_key: rustaxa_vdf::vrf::public_key_from_secret(&VRF_SECRET).unwrap(),
                commission: 0,
                description: String::new(),
                endpoint: String::new(),
                total_stake: u256_be(5_000),
                delegations: vec![rustaxa_ffi::GenesisDelegation {
                    delegator: voter_from_secret(&NODE_SECRET),
                    stake: u256_be(5_000),
                }],
            }],
            rustaxa_ffi::GenesisDposConfig {
                eligibility_balance_threshold: u256_be(1_000),
                vote_eligibility_balance_step: u256_be(1_000),
                validator_maximum_stake: u256_be(30_000),
                minimum_deposit: Vec::new(),
                commission_change_delta: 0,
                commission_change_frequency: 0,
                delegation_delay: 0,
                dag_vdf_sortition_total_vote_count_until_period: 0,
            },
        )
        .unwrap();

        (service, final_chain)
    }

    fn u256_be(value: u64) -> Vec<u8> {
        let bytes = ethereum_types::U256::from(value).to_big_endian();
        let mut padded = [0_u8; 32];
        padded[32 - bytes.len()..].copy_from_slice(&bytes);
        padded.to_vec()
    }

    fn input(vote_type: u8, step: u64, secret: [u8; 32]) -> FfiPbftVoteGenerationInput {
        FfiPbftVoteGenerationInput {
            block_hash: [0x11; 32],
            vote_type,
            period: 9,
            round: 1,
            step,
            node_secret: secret,
            vrf_secret: VRF_SECRET,
            expected_voter: voter_from_secret(&secret),
            expected_vrf_public_key: rustaxa_vdf::vrf::public_key_from_secret(&VRF_SECRET).unwrap(),
        }
    }

    fn input_with_period(
        vote_type: u8,
        step: u64,
        secret: [u8; 32],
        period: u64,
    ) -> FfiPbftVoteGenerationInput {
        FfiPbftVoteGenerationInput {
            block_hash: [0x11; 32],
            vote_type,
            period,
            round: 1,
            step,
            node_secret: secret,
            vrf_secret: VRF_SECRET,
            expected_voter: voter_from_secret(&secret),
            expected_vrf_public_key: rustaxa_vdf::vrf::public_key_from_secret(&VRF_SECRET).unwrap(),
        }
    }

    #[test]
    fn bridge_generates_signed_vote_bytes() {
        let vote = pbft_generate_signed_vote(input(3, 3, NODE_SECRET)).unwrap();
        assert!(vote.accepted);
        assert!(!vote.has_weight);
        assert_eq!(vote.vote_type, 3);
        assert!(!vote.vote_rlp.is_empty());
    }

    #[test]
    fn bridge_service_generates_weighted_vote_bytes() {
        let (service, final_chain) = test_fixture();
        let vote = service
            .pbft_service_generate_signed_vote_with_weight(
                &final_chain,
                input_with_period(1, 1, NODE_SECRET, 1),
                50,
                100,
            )
            .unwrap();
        assert!(vote.accepted);
        assert!(vote.has_weight);
        assert!(vote.weight > 0);
    }

    #[test]
    fn bridge_service_generates_weighted_zero_stake_vote() {
        let (service, final_chain) = test_fixture();
        let vote = service
            .pbft_service_generate_signed_vote_with_weight(
                &final_chain,
                input_with_period(1, 1, NODE_SECRET_ZERO_STAKE, 1),
                50,
                100,
            )
            .unwrap();
        assert_eq!(
            vote.status,
            rustaxa_consensus::pbft_vote_generation::PbftVoteGenerationStatus::ZeroStake.as_u8()
        );
        assert!(!vote.accepted);
    }

    #[test]
    fn bridge_service_reports_zero_weight_as_typed_generation_status() {
        let (service, final_chain) = test_fixture();
        let vote = service
            .pbft_service_generate_signed_vote_with_weight(
                &final_chain,
                input_with_period(1, 1, NODE_SECRET, 1),
                0,
                0,
            )
            .unwrap();
        assert_eq!(
            vote.status,
            rustaxa_consensus::pbft_vote_generation::PbftVoteGenerationStatus::ZeroWeight.as_u8()
        );
        assert!(!vote.accepted);
    }

    #[test]
    fn bridge_service_preserves_identity_error_before_zero_stake_status() {
        let (service, final_chain) = test_fixture();
        let mut mismatched = input_with_period(1, 1, NODE_SECRET, 1);
        mismatched.expected_voter = voter_from_secret(&NODE_SECRET_ZERO_STAKE);
        let vote = service
            .pbft_service_generate_signed_vote_with_weight(&final_chain, mismatched, 50, 100)
            .unwrap();
        assert_eq!(
            vote.status,
            rustaxa_consensus::pbft_vote_generation::PbftVoteGenerationStatus::NodeSecretMismatch
                .as_u8()
        );
        assert!(!vote.accepted);
    }

    #[test]
    fn bridge_service_generates_weighted_vote_from_future_period() {
        let (service, final_chain) = test_fixture();
        assert!(service
            .pbft_service_generate_signed_vote_with_weight(
                &final_chain,
                input_with_period(1, 1, NODE_SECRET, 99),
                50,
                100
            )
            .is_err());
    }

    #[test]
    fn bridge_service_generates_weighted_vote_from_period_zero() {
        let (service, final_chain) = test_fixture();
        assert!(service
            .pbft_service_generate_signed_vote_with_weight(
                &final_chain,
                input_with_period(1, 1, NODE_SECRET, 0),
                50,
                100
            )
            .is_err());
    }

    #[test]
    fn bridge_service_rejects_invalid_weighted_vote_type() {
        let (service, final_chain) = test_fixture();
        let invalid_input = input_with_period(255, 1, NODE_SECRET, 1);
        assert!(service
            .pbft_service_generate_signed_vote_with_weight(&final_chain, invalid_input, 50, 100)
            .is_err());
    }
}
