[package]
name = "rustaxa-bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0"
rustaxa-consensus = { path = "../rustaxa-consensus" }
rustaxa-storage = { path = "../rustaxa-storage" }
rustaxa-types = { path = "../rustaxa-types" }
rustaxa-vdf = { path = "../rustaxa-vdf" }
anyhow = "1.0.100"
ethereum-types = "0.16.0"
rlp = "0.6"

[build-dependencies]
cxx-build = "1.0"

[dev-dependencies]
