[package]
name = "rustaxa-consensus"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
ethereum-types = { version = "0.16.0", features = ["rlp"] }
keccak-hasher = "0.15.3"
rlp = "0.6"
rustaxa-storage = { version = "0.1.0", path = "../rustaxa-storage" }
rustaxa-types = { version = "0.1.0", path = "../rustaxa-types" }
tiny-keccak = { version = "2.0", features = ["keccak"] }
triehash = "0.8.4"
