name: Rustaxa Builder
on:
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile.builder'
      - 'conanfile.py'
      - 'scripts/**'
      - '.github/workflows/rustaxa-builder.yml'
  workflow_dispatch:  # Manual trigger option

env:
  LLVM_VERSION: 19

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Image
      id: build
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile.builder
        push: true
        tags: ghcr.io/${{ github.repository }}/rustaxa-builder:latest
        build-args: |
          LLVM_VERSION=${{ env.LLVM_VERSION }}
