name: Rustaxa Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/rustaxa-builder:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
      env:
        HOME: /root
    steps:
    - uses: actions/checkout@v4
    - name: Build Rustaxa
      run: |
        echo "Conan config home: $(conan config home)"
        echo "Available profiles: $(conan profile list)"
        mkdir -p build
        conan install . -s "build_type=RelWithDebInfo" -s "&:build_type=Debug" --profile:host=clang --profile:build=clang --build=missing --output-folder=build
        cd build
        cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DTARAXA_ENABLE_LTO=OFF -DTARAXA_STATIC_BUILD=ON -DTARAXA_GPERF=ON
        cmake --build build --target taraxad -j
